= Authentication practices with Tekton
:toc: left
:toclevels: 5
:source-highlighter: rouge

The __upstream__ official documentation around authentication is available https://tekton.dev/docs/pipelines/auth/[here]. It mainly focus on authenticating through annotated secrets and service accounts. This document will try to explore the different way to use "secrets" for authentication in your ``Pipeline`` and ``Task``.

There is at least three ways to use secrets to authenticate to Github or Docker or.

- Using secrets and workspaces **highly recommended**
- Using a `ServiceAccount` **recommended**
- Using `VolumeMount` **not recommended**

== Using `Secret`(s) and `Workspace`(s)

This is the most flexible approach, especially if you use the __optional__ workspace feature.
The general idea behind this approach is:
- We use a workspace to bind a secret
- In the `Task` definition, we tell the command line (through a flag or an environment variable) where to find the secret content (aka the authentication content).

We'll take the example with a very simple `git-clone` Task, as well as a very simple `docker build`, but it can apply to anything else.

=== A git clone example

For this example, we assume we are using `git` with `ssh` to authenticate. Later in the document, we will show different approaches.

[source,yaml]
----
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
spec:
  workspaces:
    - name: output
      description: The git repo will be cloned onto the volume backing this Workspace.
    - name: ssh-directory # (1)
      description: |
        A .ssh directory with private key, known_hosts, config, etc. Copied to
        the user's home before git commands are executed. Used to authenticate
        with the git remote when performing the clone. Binding a Secret to this
        Workspace is strongly recommended over other volume types
  params:
    - name: url
      description: Repository URL to clone from.
      type: string
    - name: revision
      description: Revision to checkout. (branch, tag, sha, ref, etc...)
      type: string
      default: ""
    - name: gitInitImage
      description: The image providing the git-init binary that this Task runs.
      type: string
      default: "gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.37.0"
  results:
    - name: commit
      description: The precise commit SHA that was fetched by this Task.
    - name: url
      description: The precise URL that was fetched by this Task.
  steps:
    - name: clone
      image: "$(params.gitInitImage)"
      script: |
        #!/usr/bin/env sh
        set -eu
        # This is necessary for recent version of git
        git config --global --add safe.directory '*'
        # (2)
        cp -R "$(workspaces.ssh-directory.path)" "${HOME}"/.ssh
        chmod 700 "${HOME}"/.ssh
        chmod -R 400 "${HOME}"/.ssh/*
        CHECKOUT_DIR="$(workspaces.output.path)/"
        /ko-app/git-init \
          -url="$(params.url)" \
          -revision="$(params.revision)" \
          -path="${CHECKOUT_DIR}"
        cd "${CHECKOUT_DIR}"
        RESULT_SHA="$(git rev-parse HEAD)"
        EXIT_CODE="$?"
        if [ "${EXIT_CODE}" != 0 ] ; then
          exit "${EXIT_CODE}"
        fi
        printf "%s" "${RESULT_SHA}" > "$(results.commit.path)"
        printf "%s" "$(params.url)" > "$(results.url.path)"
----

1. Defines the workspace ; here the name is `ssh-directory`, and the description explain how should the secret be created.
An example of an ssh secret with a `ed25519` private key.
+
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: my-github-ssh-credentials
type: Opaque
data:
  id_ed25519: # […]
  known_hosts: # […]
  # config: # […] # optional
----
This can be created with the following command-line:
+
[source,bash]
----
$ kubectl create secret generic my-github-ssh-credentials \
  --from-file=id_ed25519=/path/to/.ssh/id_ed25519 \
  --from-file=known_hosts=/path/to/.ssh/known_hosts
secret/my-github-ssh-credentials created
----

2. In the `script`, we are copying the content of the secret (as a folder) to `${HOME}/.ssh` which is the standard folder where `ssh` (and thus `git`) will look for credentials.

[source,bash]
----
$ tkn task start git-clone \
      --param url=git@github.com:vdemeester/buildkit-tekton \
      --workspace name=output,emptyDir="" \
      --workspace name=ssh-directory,secret=my-github-ssh-credentials \
      --use-param-defaults --showlog
TaskRun started: git-clone-run-kt7fv
Waiting for logs to be available...
[clone] {"level":"warn","ts":1657102809.7319033,"caller":"git/git.go:273","msg":"URL(\"git@github.com:vdemeester/buildkit-tekton\") appears to need SSH authentication but no SSH credentials have been provided"}
[clone] {"level":"info","ts":1657102813.1506214,"caller":"git/git.go:178","msg":"Successfully cloned git@github.com:vdemeester/buildkit-tekton @ e6afd054a907ee447a040c6e95f23fabe038ce6d (grafted, HEAD) in path /workspace/output/"}
[clone] {"level":"info","ts":1657102813.1600826,"caller":"git/git.go:217","msg":"Successfully initialized and updated submodules in path /workspace/output/"}
----

Note that the warning `URL(\"git@github.com:vdemeester/buildkit-tekton\") appears to need SSH authentication but no SSH credentials have been provided` appears because the entrypoint didn't see any credentials coming from the annotated secrets attached to a `ServiceAccount` (see <<Using `ServiceAccount`(s)>>). It can safely be ignored in that case.

=== A docker configuration

For this example, we will be using an existing docker configuration file to be used inside a `Task`, similar to the <<A git clone example>> example.
The `Task` definition is slightly similar to the <<A git clone example>> one. Here we will use `skopeo` to copy an image to our own repository — it could be applied to other tools (`podman`, `buildah`, `docker`, …), basically any tool that is capable of reading a docker client configuration file.

[source,yaml]
----
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: skopeo-copy
spec:
  workspaces:
    - name: dockerconfig # (1)
      description: Includes a docker `config.json`
  steps:
    - name: clone
      image: quay.io/skopeo/stable:v1.8.0
      env:
      - name: DOCKER_CONFIG
        value: $(workspaces.dockerconfig.path) # (2)
      script: |
        #!/usr/bin/env sh
        set -eu
        skopeo copy docker://docker.io/library/ubuntu:latest docker://docker.io/vdemeester/ubuntu-copy:latest
----

1. Similar to <<A git clone example>>, we define a workspace that should contain a `config.json` file. For a secret, this means a key named `config.json`.
An example of an ssh secret with a `ed25519` private key.
+
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: regcred
type: Opaque
data:
  config.json: # […]
----
This can be created with the following command-line:
+
[source,bash]
----
$ kubectl create secret generic regcred \
  --from-file=config.json=/path/to/.docker/config.json
secret/regcred created
----

2. Here we are just setting the `DOCKER_CONFIG` environment variable to point to the `dockerconfig` workspace path. `skopeo` (as a lot of docker-ish client) do read this environment variable to get the docker client configuration information, and in our case, the authentication informations.

[source,bash]
----
$ tkn task start skopeo-copy --workspace name=dockerconfig,secret=regcred --showlog
TaskRun started: skopeo-copy-run-cfg7l
Waiting for logs to be available...
[clone] DOCKER_CONFIG=/workspace/dockerconfig
Getting image source signatures
[clone] Copying blob sha256:405f018f9d1d0f351c196b841a7c7f226fb8ea448acd6339a9ed8741600275a2
[clone] Copying config sha256:27941809078cc9b2802deb2b0bb6feed6c236cde01e487f200e24653533701ee
[clone] Writing manifest to image destination
[clone] Storing signatures
----

=== With optional workspaces

TODO

== Using `ServiceAccount`(s)

TODO

== Using `VolumeMount`(s)

TODO
